name: Connecting the Dots
description: You have to trust that the dots will somehow connect in your future
meta_description: "Connecting the Dots"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'https://yangxuhui.github.io'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'yangxuhui.github.io'
# author:         'yangxuhui'
